### ISSUE TITLE
Afficher des messages d'erreur user-friendly pour les erreurs de parsing YAML

### ISSUE THREAD

**Issue by Morendil** [sgmap/syso#5]

**Comment by laem** [comment]
Les YAML sont chargés avec le loader YAML de Webpack, qui utilise js-yaml. 
L'erreur doit être récupérable quelque part dans ces tuyaux...

**Comment by laem** [comment]
@Morendil Bonne nouvelle !

Avec la mise à jour de yaml-loader, la trace évolue : 

```
WARNING in ./règles/rémunération-travail/cdd/majoration-chomage.yaml
Module build failed: Error
    at generateError (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:308:7)
    at readBlockMapping (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1071:9)
    at composeNode (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/home/mama/dev/sgmap/actifs/syso/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
 @ ./règles/rémunération-travail/cdd .yaml$
 @ ./source/engine/load-rules.js
 @ ./source/engine/rules.js
 @ ./source/reducers.js
 @ ./source/entry.js
 @ multi webpack-dev-server/client?http://localhost:3000/ webpack/hot/only-dev-server react-hot-loader/patch babel-polyfill ./source/entry.js

```
devient : 
```

 WARNING in ./règles/rémunération-travail/cdd/majoration-chomage.yaml
 duplicated mapping key at line 24, column -75:
               événement . poursuite du CDD en CDI:
               ^
  @ ./règles/rémunération-travail/cdd .yaml$
  @ ./source/engine/load-rules.js
  @ ./source/engine/rules.js
  @ ./source/reducers.js
  @ ./source/entry.js
  @ multi webpack-dev-server/client?http://localhost:3000/ webpack/hot/only-dev-server react-hot-loader/patch babel-polyfill ./source/entry.js
```

**Comment by laem** [comment]
On pourra faire mieux, mais je ferme. N'hésite pas à rouvrir et préciser le besoin @Morendil
